blank_issues_enabled: false
contact_links:
  - name: Project Discussion
    url: https://github.com/ttugdsc/HackWesTX-Official-Repo/discussions
    about: Talk about general project features and ideas here.
  - name: ACM Development
    url: https://acmutd.co/team.html
    about: More information about the core HackPortal maintainers.
  - name: Inquiries for Maintainers
    url: development@acmutd.co
    about: If you have a question specific to the maintainers, contact them here.
